// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9-n6hpqAqyXS3_gmcAug_BMpejpjfDnE',
    appId: '1:216260957858:web:1142246ca20a8170a029fb',
    messagingSenderId: '216260957858',
    projectId: 'catsshop',
    authDomain: 'catsshop-57904.firebaseapp.com',
    storageBucket: 'catsshop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD04_GnHxU27t9ONMZQkJzN5UPSjtx1Bbc',
    appId: '1:216260957858:android:1415e7f4da6e5c68a029fb',
    messagingSenderId: '216260957858',
    projectId: 'catsshop',
    storageBucket: 'catsshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTAlWHN9c5mFM0KH_9jNr91XgMS6WkU-c',
    appId: '1:216260957858:ios:8bade6c7067e92f8a029fb',
    messagingSenderId: '216260957858',
    projectId: 'catsshop',
    storageBucket: 'catsshop.appspot.com',
    iosBundleId: 'com.example.theCatsShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTAlWHN9c5mFM0KH_9jNr91XgMS6WkU-c',
    appId: '1:216260957858:ios:59cf6c9a534e8f85a029fb',
    messagingSenderId: '216260957858',
    projectId: 'catsshop',
    storageBucket: 'catsshop.appspot.com',
    iosBundleId: 'com.example.theCatsShopApp.RunnerTests',
  );
}
